[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tlink-rp.x",
]
runner = "elf2uf2-rs --deploy --serial --term --verbose"
#runner = "probe-rs run --chip RP2040_SELFDEBUG"
#runner = "probe-rs run --chip RP2040"
#runner = "probe-rs run --chip RP2040 --protocol swd"
#runner = "probe-rs run --chip RP2040_SELFDEBUG --protocol swd"

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+
